jupyter/jupyter_core

jupyter_core/paths.py
jupyter_core/tests/test_paths.py

makes it easier to control a deployment or test environment

define JUPYTER_DATA_DIR, JUPYTER_RUNTIME_DIR env

---

jupyter_core/application.py

back to back with :
https://github.com/ipython/ipython/pull/8324

don't swallow sys.exit

---

jupyter_core/application.py
jupyter_core/paths.py
jupyter_core/tests/test_application.py
jupyter_core/tests/test_paths.py

accessible as a list via `paths.jupyter_path()`

add support for JUPYTER_PATH

---

jupyter_core/application.py
jupyter_core/tests/test_application.py

closes jupyter/jupyter_nbconvert#7

allow specifying config file with `--config FILE`

---

jupyter_core/application.py
jupyter_core/command.py
jupyter_core/paths.py
jupyter_core/tests/test_command.py

via `jupyter --config-dir`, etc.
Full paths can be retrieved as JSON with
jupyter --paths --json

add CLI for retrieving jupyter paths

---

jupyter_core/application.py
jupyter_core/tests/test_application.py

Todo:
Failing test. 
ping @takluyver.

Fix config file loading in nbconvert.

---

.travis.yml
requirements.txt

requirements.txt can go away again

traitlets is released

---

jupyter_core/command.py
jupyter_core/tests/test_command.py

i.e. include `nbextension-install` IFF `nbextension` is not defined.
closes #15

list subcommands with a hyphen in the name

---

CONTRIBUTING.md
MANIFEST.in

add MANIFEST.in, CONTRIBUTING.md

---

jupyter_core/application.py

Use instances of traits instead of trait classes

---

jupyter_core/application.py

use raw_input on Python 2

---

jupyter_core/command.py

argparse version action prints to stderr on py2
closes jupyter/jupyter#19

ensure version is printed to stdout

---

setup.py

add test files to package data

---

jupyter_core/migrate.py

check if custom.js/css exist before migrating them

---

docs/changelog.rst
docs/index.rst

I'll release 4.0.5 when this is merged

add changelog

---

jupyter_core/migrate.py

fix local variable 'custom_css_empty' referenced before assignment

---

.travis.yml
jupyter_core/migrate.py
jupyter_core/tests/test_migrate.py

Pretty sure that will fix jupyter/notebook#646
Need to write a test.

Use unicode everywhere, because unicode is good, python2 is bad

---

examples/jupyter-completion.bash

Bring bash completion to jupyter form IPython.

---

docs/changelog.rst

notes for 4.1.1

---

jupyter_core/command.py

`shell=True` was used to ensure that current PATH is considered, which `shell=False` doesn't do for some reason.
cf #65, which added `shell=True`
use shutil.which to do the resolution ourselves, to avoid instantiating a shell, which can cause other problems (see jupyter/jupyter#203).

Don't use shell=True on Windows

---

docs/changelog.rst

cc @takluyver
I'll release as soon as this is merged.

Changelog for 4.2

---

docs/changelog.rst

I'll cut a release once this is merged.

Changelog entry for 4.2.1

---

jupyter_core/tests/test_migrate.py

Hat tip to @tomdz as part of #99.

locate_profile is not used in this test

---

jupyter_core/tests/test_command.py

Python scripts are not executable on Windows. This is solved here by using setuptool's way of making an exe wrapper (if setuptools is not available it will skip the relevant tests).

Fix tests on Windows

---

CONTRIBUTING.md
README.md

Describe the minimal development setup for working on the code and documentation of Jupyter Core.
Similar to https://github.com/jupyter/jupyter_client/pull/271.

README on setting up the development environment

---

.travis.yml
jupyter_core/application.py
jupyter_core/migrate.py
jupyter_core/tests/test_migrate.py
jupyter_core/utils/__init__.py

See discussion on https://github.com/jupyter/notebook/pull/2924

Add utility function ensure_dir_exists

---

docs/changelog.rst
docs/conf.py
docs/requirements.txt

The last release was in February, and there have been a few changes in master, so I'm planning to do a new release.

Changelog for 4.4.0

---

examples/jupyter-completion.bash

as per alexisdimi's suggestion in Issue #168

Update example to achieve bash 3.2 compatibility

---

docs/changelog.rst

Wrote up changelog for 4.6.1.  Here's a screen shot from a test build...

Changelog for 4.6.1

---

jupyter_core/paths.py

Help resolve https://github.com/jupyter/jupyter_client/issues/481 by skipping all file permission checks on windows when in insecure mode.
I tested as well as I can on a few system setups, so I'm reasonably sure this covers the issue. But since I never did get a reproduction of the reporting problem it's possible something else will come up later for users. Given that this makes insecure mode follow the same code path it had pre-secure check I'm hopeful this will be the last item.

Made windows permission setting / checks not run in insecure mode

---

.github/workflows/codeql-analysis.yml
docs/conf.py
jupyter_core/application.py
jupyter_core/command.py
jupyter_core/paths.py
jupyter_core/tests/test_application.py
jupyter_core/tests/test_command.py
jupyter_core/tests/test_migrate.py
jupyter_core/tests/test_paths.py
jupyter_core/troubleshoot.py

See https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository

Scanning with CodeQL from GitHub

---

docs/changelog.rst
jupyter_core/version.py

I also updated the version info file to follow more pythonic conventions.

Update changelog for 4.7

---

docs/changelog.rst

Updates the changelog for the 4.8 release.

Update changelog for 4.8

---

.github/workflows/test.yml
dev-requirements.txt
jupyter_core/tests/test_paths.py
setup.cfg

- addresses https://github.com/jupyter/jupyter_core/issues/235#issuecomment-904928193
- adds `pypy-37` to CI matrix
- adds basic coverage reporting

add pypy-3.7, py3.10-dev and pytest-cov

---

docs/changelog.rst

I'll release this early next week.

Update changelog for 4.10 Release

---

.pre-commit-config.yaml
COPYING.md
README.md
jupyter_core/command.py
jupyter_core/tests/test_async.py
jupyter_core/utils/__init__.py

(cherry picked from commit 51b8a12)

[4.x] Add run_sync and ensure_async functions

---

jupyter_core/utils/__init__.py

Mostly make sure that ensure_async is properly typed, and not justs has "Any"

Maint: Some more precise typing.

---

.pre-commit-config.yaml
jupyter_core/paths.py

Everything seem to be using relative import except this line (and the tests and scripts). Be consistent.

Remove only absolute import.

---

jupyter_core/tests/test_paths.py

cf https://github.com/platformdirs/platformdirs/releases/tag/3.0.0

Support platformdirs 3

---

jupyter_core/application.py
jupyter_core/utils/__init__.py
tests/test_application.py

Reverts jupyter/jupyter_core#381.   The PR caused #383 and we had to yank the 5.6.0 release.

Revert "Enable async JupyterApp"

---

jupyter_core/__init__.py
pyproject.toml
tests/test_command.py

Fix export of package version

---

jupyter_core/application.py

Needed for https://github.com/jupyter/jupyter_client/pull/997

Derive JupyterAsyncApp from JupyterApp

---

.github/workflows/test.yml
.pre-commit-config.yaml
CHANGELOG.md
docs/conf.py
jupyter.py
jupyter_core/__main__.py
jupyter_core/application.py
jupyter_core/command.py
jupyter_core/paths.py
jupyter_core/troubleshoot.py
jupyter_core/utils/__init__.py
jupyter_core/version.py
pyproject.toml
scripts/jupyter
scripts/jupyter-migrate
tests/test_command.py
tests/test_migrate.py
tests/test_paths.py

- precommit-ci is not sending any updates because of branch protection rules.
- Update and fix corresponding errors.
- run mypy as part of CI.

A bunch of pre-commit and CI upgrade.

---

.github/workflows/test.yml
jupyter_core/paths.py
pyproject.toml

`License :: *` are deprecated, and Funding is not via Numfocus.

Update Pyproject metadata

---

docs/api/jupyter_core.rst
docs/api/jupyter_core.utils.rst

meaningless churn from autoformatters

chore: hatch run run docs:api
