jupyter/jupyter_core

jupyter_core/paths.py
even on XP, where PROGRAMDATA is undefined, in which case fall back on sys.prefix/share/jupyter.
If there's another sensible default on XP, that would be fine, too. I'm not actually sure we support XP anymore, so this may not matter, but I don't want it possible for this list to be empty.
=> ensure SYSTEM_JUPYTER_PATH is never empty

jupyter_core/paths.py, jupyter_core/tests/test_paths.py
See http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
Runtime is different from the other XDG directories in that it's a single directory, not a search path.
=> XDG_RUNTIME_DIR, not XDG_RUNTIME_HOME

jupyter_core/application.py, jupyter_core/tests/test_application.py
with `jupyter [app] --generate-config`
By raising `NoStart` in JupyterApp.start when start shouldn't proceed, subclasses can use `super` without having to duplicate checks for whether `start` should really do anything.
=> enable generating config files

jupyter_core/command.py
- `jupyter -h` shows subcommand list
- avoid greedily interpreting `-h` if passed to `jupyter subcommand -h`
closes #11
closes #12
=> handle `jupyter -h`

jupyter_core/application.py
This makes it a bit easier to follow, in my opinion, and if a config file is specified with a full path, it should load it only once, whereas it was previously loaded again for each config directory.
=> Simplify logic for loading config files

jupyter_core/application.py
nbopen uses these. The underlying Application class already has them, they just weren't exposed by this subclass.
=> Pass kwargs through launch_instance()

jupyter_core/command.py
This error message should only show up when the error is because the command doesn't exist. I was getting the same message for a permissions error.
=> Be more selective with 'not a Jupyter command' error

dev-requirements.txt, jupyter_core/migrate.py, jupyter_core/tests/dotipython/nbextensions/myext.js, jupyter_core/tests/dotipython/profile_default/ipython_config.py, jupyter_core/tests/dotipython/profile_default/ipython_console_config.py, jupyter_core/tests/dotipython/profile_default/ipython_kernel_config.py, jupyter_core/tests/dotipython/profile_default/ipython_nbconvert_config.py, jupyter_core/tests/dotipython/profile_default/ipython_notebook_config.py, jupyter_core/tests/dotipython/profile_default/static/custom/custom.css, jupyter_core/tests/dotipython/profile_default/static/custom/custom.js, jupyter_core/tests/dotipython_empty/profile_default/ipython_config.py, jupyter_core/tests/dotipython_empty/profile_default/ipython_console_config.py, jupyter_core/tests/dotipython_empty/profile_default/ipython_kernel_config.py, jupyter_core/tests/dotipython_empty/profile_default/ipython_nbconvert_config.py, jupyter_core/tests/dotipython_empty/profile_default/ipython_notebook_config.py, jupyter_core/tests/dotipython_empty/profile_default/static/custom/custom.css, jupyter_core/tests/dotipython_empty/profile_default/static/custom/custom.js, jupyter_core/tests/test_migrate.py, scripts/jupyter-migrate, setup.py
Currently, this implements migration of config files and user-installed nbextensions, kernelspecs from IPython < 4.0 to Jupyter locations via `jupyter migrate` as:
- copy files to new locations
- if new locations already exist, do nothing
- never overwrite anything
- don't copy empty config files
- small amount of find-replace in config files for renamed classes (e.g. IPythonQtConsoleApp -> JupyterQtConsoleApp)
To figure out for this PR:
To figure out after this PR:
- When to migrate.
I want to implement migration first, and work on implicit-on-startup logic, if any, as a separate discussion.
cc @takluyver @fperez @ellisonbg
closes #2
=> WIP: implement migration

jupyter_core/application.py, jupyter_core/migrate.py, jupyter_core/tests/test_migrate.py
- use logging for migrate output instead of print
- use .jupyter/migrated to indicate that migration has happened,
and shouldn't be rechecked
- default log-level is INFO, since we seem to always want that
=> migrate config at start of applications

jupyter_core/application.py
Avoids problem with traitlets master: without this, cl_config is the same as `self.config`, so it's changed by loading the config file, and doesn't store the config values from the command line.
=> Copy cl_config before loading config from file

jupyter_core/tests/test_application.py
fails if extra args are passed to pytest
closes #32
=> don't let initialize look at sys.argv in tests

jupyter_core/tests/test_command.py
use `-m jupyter_core`
one more test failure in #32 when core hasn't been installed.
=> Don't require jupyter command to be installed

setup.py
Part of the fix for jupyter/jupyter#15 - using plain 'scripts', we don't
get the exe wrappers on Windows.
To fix it completely, we can either make the same change in all packages
installing scripts (notebook, nbconvert, qtconsole, console), or make
the recognition of subcommands a bit smarter to know about running
Python scripts without an exe wrapper. I'm inclined to do the former -
more pain right now, but probably less in the long term.
@minrk, thoughts
=> Use setuptools entry points when setuptools in use

jupyter_core/command.py
avoids listing `jupyter notebook.exe` as a subcommand
related to jupyter/jupyter#15
=> remove file-extension from subcommand list on Windows

tools/_jupyter
=> A zsh autocompleter for jupyter.

jupyter_core/command.py
Use regular Popen instead.
Windows doesn't actually allow process replacement a la unix exec, but Python provides os.exec on Windows even though it doesn't actually work. It doesn't exec, it does fork & exec, which means the parent process returns immediately, and the 'true' process is put in the background.
The alternative is to use execfile on Windows, which would behave the same as exec on \*ix, with one exception: it forces all jupyter commands to be run with the same interpreter, rather than respecting shebang lines.
closes jupyter/nbconvert#103
=> don't use exec on Windows

jupyter_core/tests/test_command.py
caused py2 import branch on all Python versions
This wasn't noticed because the `mock` package was installed anyway.
=> import typo in test_command

jupyter_core/command.py
You need to pass `shell=True` on Windows, otherwise the command won't be
looked up in `PATH`.
Without this fix I get the `jupyter: 'notebook' is not a Jupyter command` error when executing any jupyter command. Tested with latest version (4.0.6)
=> use shell=True on Windows

jupyter_core/command.py, jupyter_core/tests/test_command.py
before dispatching to subcommands
This addresses the case when jupyter is executed by absolute path and its dir is not on PATH, which would result in all subcommands not being found.
closes jupyter/notebook#448
=> ensure jupyter dir is on PATH

jupyter.py, setup.py
so that `python -m jupyter` works when jupyter_core is installed.
=> add jupyter.py

scripts/jupyter-troubleshoot
Collects and prints out the data requested in the comments for [notebook ISSUE #1103](https://github.com/jupyter/notebook/issues/1103).
The revision history was extremely short and I didn't think it was worth migrating the repo from my fork of notebook to here after the location change was suggested.
There is one small shortcoming in that I don't know what Windows installations would do with `which -a jupyter` and I did not attempt to address that at all.
=> troubleshoot script from notebook Issue #1103

jupyter_core/tests/test_migrate.py
So it does not break with Python 2.7
=> Fix encoding declaration of test_migrate.py

jupyter_core/command.py
When calling `jupyter` that was installed inside a virtual environment while that environment is not active, it is unable to locate the other executables, like `jupyter-notebook` because `execvp` uses `$PATH` instead of `sys.path` to locate the executable. `sys.path` is automatically updated by the Python interpreter to add the path to the virtual environment binaries and libraries and `$PATH` is not.
This change prepends the `$PATH` environment variable with the first entry from `sys.path` before calling `execvp` to rectify this.
NOTE: I am unfamiliar with Windows' handling of environment variables and its path, so the Windows case should be updated as well before this is merged.
=> Properly set PATH when `jupyter` is called from a symlink

.gitignore, jupyter_core/command.py, jupyter_core/tests/test_command.py
ensure that `/path/to/jupyter-subcommand` has top priority when `/path/to/jupyter subcommand` is called.
=> [proposal] Prioritize jupyter script directory for subcommands

jupyter_core/command.py
Because we reused the variable name, the error message would always say
'None not found'.
=> Fix error message when subcommand not found on Windows

docs/index.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs links for their .org -> .io migration for hosted projects

jupyter_core/command.py
It happened more than once that the error message of a failing `_execvp` was unclear to me. This branch helps that.
=> More informative error message if _execvp fails

jupyter_core/paths.py
Setting JUPYTER_NO_CONFIG=1 will ignore all custom config. I'm using the convention of taking any non-empty value as True.
Closes jupyter/notebook#1992
I also considered that maybe this should ignore anything in the data search path as well (in which case, the environment variable may need a different name). However, while nbextensions are installed in data
files, they are only loaded if they are enabled in config, so I think this should avoid loading them. We may still want to make it affect the data path too for future-proofing.
=> Add environment variable to ignore all config

docs/changelog.rst
Tiny release:
- adds JUPYTER_NO_CONFIG
- tweak error message when no subcommand is found
=> Prepare to release 4.3

examples/completions-zsh
when tab completing "jupyter notebook <TAB>" the completion suggestions should be titled "notebook command" rather than "nbextension command"
=> [zsh-completion] copy&paste mistake in description

.travis.yml, jupyter_core/troubleshoot.py
avoids reporting `pip list` for a different env (e.g. Python 2)
=> use sys.executable for pip list

dev-requirements.txt
I verified that the unit tests require neither ipython nor ipykernel. According to the discussion in #99, it makes sense to have a dependency in ipykernel though, for manual testing.
I also verified that the doc build does not depend on ipython.
Does not quite resolve #99... there is still a circular dependency, though not via `ipython` anymore.
=> Depend on ipykernel instead of ipython

docs/changelog.rst
`make linkcheck` in the `docs/` dir reports a broken link to the release tag 4.1. The release is tagged as 4.1.0.
=> Fix broken link in changelog

jupyter_core/application.py, jupyter_core/migrate.py
IPython's get_ipython_dir always returns a writable directory that exists, creating one if the default resolution isn't writable.
We don't want to trigger all of this extra logic when checking for old config files to migrate,
so reimplement a simpler IPython dir resolution without any of IPython's own migration logic.
We already had a check if `get_ipython_dir()` exists to skip migration, but this would always be True because of upstream `get_ipython_dir()`'s behavior.
closes jupyterhub/jupyterhub#1503
It's also been long enough that we could consider removing automatic migration altogether, leaving only the explicit `jupyter-migrate` command.
=> Avoid triggering extra logic in IPython.paths.get_ipython_dir when performing migration

examples/jupyter-completion.bash
When transferring from ipython, the jupyter-completion.bash file was
not adapted correctly, leading to a segfault. This patch fixes the
issue.
=> fix bash-completion code

examples/jupyter-completion.bash
Bash completion called a non-existing command "jupyter baseopts" and did not complete correctly on filenames with spaces. The two patches fix these issues.
=> bash completion tweaks

.travis.yml, jupyter_core/application.py, jupyter_core/command.py
Many users use `jupyter --version` and then report they have "jupyter
4.4" which make no sens. Instead of printing an number and existing,
print a list.
That may break people shelling you to actually get jupyter_core version,
but I believe giving users the right information is more important
=> Print multiple package version when using jupyter --version.

jupyter_core/paths.py
Extend the config paths with additional system paths from environment variable JUPYTER_CONFIG_PATH.
Motivation:
Currently Jupyter configurations are only searched at fixed system paths (sys.prefix/etc/jupyter, ...)
and jupyter_config_dir(), which is in the first place a config dir writable to the user.
For a system-wide installation of Jupyter, which is not installed at sys.prefix one needs to have the ability to add additional system config paths.
=> Enable system-wide installations of Jupyter possible at any path

.travis.yml
Even 3.4 is nearly EOL, and infrastructure like pip has dropped 3.3 support already.
Also quoted the other entries to make them strings, because my IDE was complaining that the list mixed strings and numbers.
=> Drop Python 3.3 from Travis CI

setup.cfg, setup.py
Now that there are universal wheels, the setup.py is usually only ever
executed on a developer machine, where one can assume setuptools to be
available.
This slightly simplifies the setup.py code and results less potential
surprises between different setup.py runs (i.e. what happens if you run
`setup.py install` versus `setup.py bdist_wheel` and then install).
This also contains an alternate resolution for #120.
My recommendation would be to favour this PR over #146, but I can understand if you have concerns.
Best, Thomas
Resolves #120.
Closes #146.
=> Always use setuptools in setup.py

jupyter_core/paths.py
After years of trying to make this work, I've reluctantly come to the conclusion that XDG_RUNTIME_DIR is, for us, more trouble than it's worth.
Three problems in particular have led to this:
1. When Jupyter runs as a server, e.g. with screen or nohup, XDG_RUNTIME_DIR can be deleted from under us if the user logs out. I haven't found any good way to prevent this.
2. The spec allows files to be automatically cleaned up after a few hours. In theory this can be prevented by setting the sticky bit, but it's not clear where it needs to be set, and we can't be sure that all systems actually respect that.
3. Sometimes the environment variable is automatically carried over from a context where it's accurate to a context where it's not. It's definitely not the only environment variable for which …
=> Stop using XDG_RUNTIME_DIR

jupyter_core/tests/test_paths.py
No idea how I missed this, but apparently I did.
=> Fix test for jupyter_runtime_dir without XDG_RUNTIME_DIR

jupyter_core/application.py, jupyter_core/tests/test_application.py
I was taking a look at jupyterlab/jupyterlab#5716, and found that setting the base `Application` trait `raise_config_file_errors` wasn't behaving as I expected. This is because `JupyterApp` overloads the `load_config_file` function and doesn't check this option.
A quick audit of the Jupyter ecosystem shows that there are a couple of different behaviors around this.
* [`jupyterhub`](https://github.com/jupyterhub/jupyterhub/commit/7968912a7c6dda77472af15230bf6ae40e3324b2) inherits from `Application` rather than `JupyterApp`, so the trait works as expected.
* [`IPython`](https://github.com/ipython/traitlets/pull/228) overrides `load_config_file`, and specifically checks for this option.
* Notebook and JupyterLab inherit from `JupyterApp`, and they do not respect this option.
Another option …
=> Respect the raise_config_file_errors trait and re-raise if applicable.

jupyter_core/command.py
=> Removed mechanism that change $PATH

jupyter_core/application.py, jupyter_core/tests/test_application.py
Hello,
This PR fixes warnings like this:
- DeprecationWarning: DummyConsoleApp._runtime_dir_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
=> Fix deprecation warning from traitlets

dev-requirements.txt
All usages of mock are inside "except ImportError" branches meant for
running tests under Python 2. There is no need to install mock when using Python 3.
=> Require mock only for running tests on Python 2

jupyter_core/command.py, jupyter_core/tests/test_command.py
=> Add the environment scripts directory to the list of places to search for subcommands

jupyter_core/paths.py, jupyter_core/tests/test_paths.py, setup.cfg
Moved shared code from https://github.com/jupyter/jupyter_server/pull/77 and https://github.com/jupyter/jupyter_client/pull/469 as well as some other path related utils in jupyrer_server that seemed useful in a more generic scope. No code changes made on the functions  other than converting the tests from nose.assert pattern to pytest assert pattern.
Tested on windows & ubuntu independently
=> Moved path util code from jupyter_client and jupyter_server to core

jupyter_core/paths.py
Sometimes users have home directories that contain unicode characters outside of ASCII (such as č). This leads to exception thrown in `migrate.py:migrate` namely in the line:
`        dst = dst_t.format(**env)`
because `jupyter_config_dir` and `jupyter_data_dir` do not return unicode.
=>  properly handle unicode characters in home dirs

jupyter_core/paths.py
Found that the SID obtained when using GetUserName was causing permission
issues because it wasn't the actual SID for the current user.  By changing
the call to use `GetUserNameEx` with a parameter of `NameSamCompatible`,
the SID that was returned did indeed correspond to the current user.  In
addition, analysis of the file using Windows explorer also showed the SID
being resolved to the current user's Windows ID, rather than a raw SID (as
before).
Co-authored-by: snapo <6347922+snapo@users.noreply.github.com>
=> Use GetUserNameEx to get SID of current user to secure win32 files

jupyter_core/paths.py, jupyter_core/tests/test_paths.py
Some filesystems (CIFS) auto-enable execute bits on files.  As
a result, we should tolerate execute on owner (but only owner).
Special thanks to @hroncok for providing the missing tidbits to this issue! (Pun intended)
Closes: #172
=> Tolerate execute bit on owner when writing file

readthedocs.yml
Doing `setup.py install` is blocked to work around setuptools problems, and doing `pip install .` instead can seemingly only be configured through the YAML file.
=> Add readthedocs YAML config

.travis.yml
Travis runtimes are interesting.  Why does `pip install -r requirements.txt` take several times longer on Py38 and nightly than all other Python versions? https://travis-ci.org/jupyter/jupyter_core/builds/603413767?utm_source=github_status&utm_medium=notification
=> Travis CI: Add Python 3.7 and 3.8 and remove the EOL 3.4

jupyter_core/paths.py
On [Nextjournal](https://nextjournal.com/) we use a standard connection file which is mounted to docker containers in order to support Jupyter runtimes.  Since the addition of `secure_write` we can get an initial startup just fine by setting permissions on the file.  However, with some Jupyter kernels it seems the Sticky Bit gets set, and this persists on the mounted file through restarts and resets, causing `secure_write` to fail:
```
RuntimeError: Permissions assignment failed for secure file: '/runtimes/jupyter/kernel_connection.json'.Got '0o1600' instead of '0o0600'
```
I don't think the Sticky Bit is a security risk(?), so I see no reason it shouldn't be ignored.  [Tested the fork](https://nextjournal.com/a/LnBMKtooyHaE7id2qrbrG?token=RjwFVRya7ycP1uQ3E9xCyw), and this change does …
=> Ignore sticky bit when validating permissions.

jupyter_core/application.py, jupyter_core/paths.py
Per a [previous discussion](https://github.com/jupyter/jupyter_client/issues/507), this change enables users to bypass the file permissions enforcement within `secure_write()`.  This has become an issue when secure files reside on filesystems that automatically promote file permissions to o777 and prevents changes to those settings.  In such cases, users can prevent enforcement by setting environment variable `JUPYTER_ALLOW_INSECURE_WRITES` to true (default = false).
I debated on the polarity of the env variable name.  I liked `JUPYTER_ENFORCE_SECURE_WRITES` but felt having a variable that defaults to True was a bit odd.  Also, I felt that users setting something to skip security by having to set it to True was a more explicit action.
In looking at testing this change, I couldn't find a …
=> Add ability to allow insecure writes

jupyter_core/troubleshoot.py
This makes it easier to re-create the exact conditions as the user reporting an issue by running `conda env create --file environment.yml`.  Example output:
<details>
<pre>
conda env:
name: /tmp/conda_envs/95dbb6925f9d9cc84dbb167d
channels:
- conda-forge
- defaults
dependencies:
- appnope=0.1.0=py36h9f0ad1d_1001
- attrs=19.3.0=py_0
- backcall=0.1.0=py_0
- bleach=3.1.4=pyh9f0ad1d_0
- ca-certificates=2020.4.5.1=hecc5488_0
- certifi=2020.4.5.1=py36h9f0ad1d_0
- decorator=4.4.2=py_0
- defusedxml=0.6.0=py_0
- entrypoints=0.3=py36h9f0ad1d_1001
- importlib-metadata=1.6.0=py36h9f0ad1d_0
- importlib_metadata=1.6.0=0
- ipykernel=5.2.1=py36h95af2a2_0
- ipython=7.13.0=py36h9f0ad1d_2
- ipython_genutils=0.2.0=py_1
- jedi=0.17.0=py36h9f0ad1d_0
- jinja2=2.11.2=pyh9f0ad1d_0
- …
=> Add conda env export info

jupyter_core/paths.py
This removes the `strtobool` import from `distutils.util`, used for evaluating the value of the `JUPYTER_ALLOW_INSECURE_WRITES` environment variable, and replaces it by a straightforward expression. See comments in #193 for the justification.
Strictly speaking, this breaks backwards compatibility because the proposed implementation:
1. only accepts "true" (ignoring case) and "1" as `True` values, whereas the previous implementation also accepted "y", "yes", "t", and "on".
2. stores a `True`/`False` boolean in the `allow_insecure_writes` variable, whereas the previous implementation stored integer numbers `1`/`0`.
To me (as an outsider of the jupyter project), this does not seem to be a problem since these implementation details were only available from the source code, and internally the …
=> Replace strtobool to avoid distutils import

jupyter_core/command.py, jupyter_core/paths.py, jupyter_core/tests/test_command.py, jupyter_core/tests/test_paths.py
This addresses the long-standing problem we have when running Jupyter in virtual environments, where a given user will have many virtual environments. In this case, conceptually the environment-level paths are more specific than user-level paths, but Jupyter still treats the user-level paths as more specific. If a user typically uses virtual environments, they can set this flag in their environment and Jupyter will prioritize environment-level paths over user-level paths.
So now, setting `JUPYTER_ENV_PRIORITY` environment variable to anything except 'n', 'no', 'false', 'off', '0', or '0.0' makes Jupyter use environment paths first, *then* user-level paths (including JUPYTER_DATA_DIR or JUPYTER_CONFIG_DIR, if specified), then system locations.
We also fix an inconsistency between …
=> Add an environment variable flag to switch the user and environment path order

jupyter_core/command.py, jupyter_core/paths.py
That was technically a breaking change, so should not have been done in a minor release.
We can make all environment variable boolean flags consistent in 5.0.
@kevin-bates - after thinking more about this, I think we should play it very safe and conservative here, and preserve behavior until 5.0.
=> Revert the change to parsing in JUPYTER_NO_CONFIG in #199

jupyter_core/paths.py, jupyter_core/tests/test_paths.py
This allows the user to delete the file without elevating / UAC, c.f. https://docs.microsoft.com/en-us/windows/win32/fileio/file-security-and-access-rights
=> [win32_restrict_file_to_user] allow user to delete file

jupyter_core/command.py, jupyter_core/tests/test_command.py
Previously, when a command was not found, Jupyter printed a traceback on the user:
$ jupyter foobar
Traceback (most recent call last):
File "/usr/bin/jupyter", line 33, in <module>
sys.exit(load_entry_point('jupyter-core==4.6.3', 'console_scripts', 'jupyter')())
File "/usr/lib/python3.9/site-packages/jupyter_core/command.py", line 247, in main
command = _jupyter_abspath(subcommand)
File "/usr/lib/python3.9/site-packages/jupyter_core/command.py", line 133, in _jupyter_abspath
raise Exception(
Exception: Jupyter command `jupyter-foobar` not found.
Generally, I believe users should only see tracebacks when they are debugging
stuff or when there is an unexpected "crash".
In Fedora, such traceback is detected as crash by the automatic bug reporting tool.
Now, an error message is printed to …
=> Command not found will no longer traceback

.github/workflows/codeql-analysis.yml
Adds permissions metadata to `codeql-analysis` workflow since organization-level permissions are read-only.
=> Enable appropriate permissions for CodeQL workflow

jupyter_core/command.py, jupyter_core/tests/test_command.py
prior to this commit:
```
$ jupyter help
Jupyter command `jupyter-help` not found.
$ echo $?
1
```
and
```
$ jupyter
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
[--paths] [--json] [--debug]
[subcommand]
jupyter: error: one of the arguments --version subcommand --config-dir --data-dir --runtime-dir --paths is required
$ echo $?
1
```
With this PR:
```
$ jupyter help
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
[--paths] [--json] [--debug]
[subcommand]
Jupyter: Interactive Computing
positional arguments:
subcommand     the subcommand to launch
optional arguments:
-h, --help     show this help message and exit
--version      show the jupyter command's version and exit
--config-dir   show Jupyter config dir
--data-dir     show …
```
=> Print full usage on missing or invalid commands

jupyter_core/command.py
Seems like we should include `jupyter_server` in the `jupyter --version` output.  While updating, I made the following changes:
1. Use package names and not logical "application" names since the latter introduced inconsistencies and package names are what folks equate with version information.
2. Sort packages alphabetically
3. Add `jupyter_server` and `nbclient`
4. Add indicator that these are "selected packages" (i.e., it's not a complete list) 
Here's the before and after output (on my system)...
Before...
```
$ jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : not installed
ipython          : 7.23.0
ipykernel        : 5.5.5
jupyter client   : 7.0.0.dev
jupyter lab      : 3.0.4
nbconvert        : 6.0.7
ipywidgets       : not installed
nbformat …
```
=> Update packages listed in jupyter --version

jupyter_core/paths.py, setup.cfg
Fix #226 and #229
This PR makes `jupyter_core` compatible with PyPy on Win32.  The main issue is that the `pywin32` package does not yet support PyPy (https://github.com/mhammond/pywin32/issues/1289).
Changes:
1. add an alternative Ctypes implementation of the `win32_restrict_file_to_user` function, which is used as a fallback if the `pywin32` package is not installed
2. change `install_requires` to exclude `pywin32` on PyPy
3. allow `AttributeError: 'stat_result' object has no attribute 'st_file_attributes'` to pass silently
Tested with pypy3.7-v7.3.5.
=> Remove dependency on pywin32 package on PyPy

jupyter_core/application.py
gets `--show-config` and `--show-config-json` options for all Applications when using traitlets 5
=> inherit base aliases/flags from traitlets Application

jupyter_core/paths.py, jupyter_core/tests/mocking.py, jupyter_core/tests/test_paths.py
This fixes starting jupyter lab and notebook on windows systems when python is installed from the Microsoft Store.
jupyterlab/jupyterlab#9250
jupyter-server/jupyter_server#435
jupyter/notebook#5996
The following runtime dir is not accessible outside of python as shown in https://github.com/jupyterlab/jupyterlab/issues/9250#issuecomment-813693491
```
runtime:
C:\Users\bussmann\AppData\Roaming\jupyter\runtime
```
Tested on https://github.com/florianbussmann/notebook/commit/5a3be036b2d364059bdabda90fdef1a480d6a24e the runtime dir used by jupyter-core in https://github.com/florianbussmann/jupyter_core/commit/ad09dbf52ed1f66f3f090897195d2382600178a1 is accessible
```
(.venv) C:\Users\bussmann\source\florianbussmann\notebook>jupyter --paths
config:
C:\Users\bussmann\.jupyter …
```
=> Return canonical path when using %APPDATA% on NT

docs/changelog.rst, jupyter_core/paths.py, jupyter_core/tests/test_paths.py
As discussed in #235, perhaps the best thing to do to give best-effort support for pypy and help users to understand the current limitations is to trigger a warning when we know we cannot give good results.
=> Trigger warning when trying to check hidden file status on PyPy

jupyter_core/tests/test_paths.py
Fixes https://github.com/jupyter/jupyter_core/issues/239
It looks like 2a08a19 removed the lowercasing of the username, and in this test the username is compared to the explicitly lowercased username, leading to a test failure on conda-forge.
=> Fix windows test regression.

jupyter_core/application.py, jupyter_core/migrate.py, jupyter_core/paths.py, jupyter_core/tests/test_application.py, jupyter_core/tests/test_migrate.py, jupyter_core/tests/test_paths.py
Having enabled `PYTHONWARNDEFAULTENCODING` on Python 3.10, I now get yelled at (which is a good thing!) whenever Python opens a file in text mode without an encoding specified, implicitly falling back on the locale. It just happened when calling `jupyter server --generate-config`, so I took a bit of time to add explicit encoding arguments to open calls in `jupyter_core`.
Please review if UTF-8 is the appropriate encoding in all cases, I'm not otherwise familiar with the codebase, so it's not always easy for me to see. Most of the calls seem to handle Python / CSS / JS files, where UTF-8 should be appropriate, but one of the functions I'm not entirely sure about is `paths.secure_write`, which can probably be used to write lots of different files (though that in turn means it can be used to …
=> Add explicit encoding in open calls

jupyter_core/paths.py
This PR moves the initialization of the home_dir variable, so that this logic will not get hit if `JUPYTER_CONFIG_DIR` or `JUPYTER_NO_CONFIG` are set in the environment (this helps to avoid any OS level issues accessing or resolving default file paths when the config directory path is already being set explicitly as an environment variable)
=> jupyter_config_dir - reorder home_dir initialization

setup.cfg
Setuptools is not including `juptyer_core/*.py` files.
```
Traceback (most recent call last):
File "/build/pytest-of-nixbld/pytest-0/test_argv00/a/jupyter", line 1, in <module>
from jupyter_core import command; command.main()
ModuleNotFoundError: No module named 'jupyter_core'
```
=> Include all files from `jupyter_core`

.github/workflows/test.yml, .pre-commit-config.yaml, MANIFEST.in, README.md, dev-requirements.txt, jupyter_core/tests/test_command.py, jupyter_core/tests/test_paths.py, pyproject.toml, setup.cfg
- Improve test matrix
- Add concurrency limit handling for GitHub Actions
- Add cron job to run tests daily
- Use base-setup from maintainer-tools to handle python version, caching, and pip upgrades
- Add tests for minimum versions, pre-releases, and sdist testing
- Update pytest config and handle warnings
=> Clean up CI

jupyter_core/version.py, pyproject.toml
Hatch is newly added pypa backend with more flexibility, and helps avoid https://github.com/pypa/pip/issues/11110, which is breaking builds.
=> Use hatch backend

jupyter_core/paths.py
The current `is_hidden` implementation considers the path `path/to/my/./file.txt` to be hidden, while it's not. This PR fixes it by normalizing the paths prior to compute the `is_hidden` logic.
Similar fix in `jupyter_server` https://github.com/jupyter-server/jupyter_server/pull/886
=> is_hidden: Use normalized paths

.github/workflows/test.yml, pyproject.toml
=> Fix inclusion of jupyter file and check in CI

jupyter_core/command.py, jupyter_core/paths.py, jupyter_core/tests/test_command.py, jupyter_core/tests/test_paths.py
We make the assumption that if we are in a virtual environment, we should prioritize the environment-level sys.prefix over the user-level paths. The user can opt out of this behavior by setting JUPYTER_PREFER_ENV_PATH, which takes precedence over our autodetection.
Fixes #283
=> Try to detect if we are in a virtual environment and change path precedence accordingly

README.md
Got a 404 clicking this link, updated it to what I believe is the most up-to-date one
=> Update broken link to `Contributing` guide

jupyter_core/application.py, jupyter_core/paths.py, jupyter_core/tests/test_paths.py
=> Add current working directory as first config path

.pre-commit-config.yaml, jupyter_core/command.py, jupyter_core/paths.py, jupyter_core/tests/test_paths.py, jupyter_core/utils/__init__.py, pyproject.toml
=> Use platformdirs for path locations

.github/workflows/test.yml, .pre-commit-config.yaml, pyproject.toml
Align with what conda-forge is doing, and limit our support to 4 versions of Python.
cf [conda-forge.org/docs/user/announcements.html#dropping-python-3-7](https://conda-forge.org/docs/user/announcements.html#dropping-python-3-7)
=> Require Python 3.8+

jupyter_core/tests/test_async.py, jupyter_core/utils/__init__.py
- `ensure_async` is used in `jupyter-client`, `jupyter-server` and `nbclient`.
- `run_sync` is used in `jupyter-client` and `nbclient`.
See https://github.com/jupyter/nbclient/pull/259.
=> Add run_sync and ensure_async functions

.github/dependabot.yml, .github/workflows/test.yml, .pre-commit-config.yaml, jupyter_core/application.py, jupyter_core/paths.py, pyproject.toml
cf https://github.com/jupyter-server/jupyter_server/pull/1114
=> Adopt ruff and address lint

.pre-commit-config.yaml, jupyter_core/utils/__init__.py
in the following
```python
async def hello():
return 1
```
`hello` is a coroutine function, and `hello()` a coroutine. Fix the vocabulary and ensure that the function is properly used.
=> MAINT: Coro is not coro-function.

jupyter_core/tests/test_command.py, jupyter_core/tests/test_paths.py
See #231
This attempts to make our test environment more reproducible by setting the environment variables to a known state before each function run.
=> Clear the test environment before each function run

jupyter_core/paths.py
any error means it didn't work and we should move on
closes #334
=> Suppress any exception in _do_i_own shortcut

jupyter_core/application.py, jupyter_core/migrate.py
In particular f-string:
There are many reason not to use f-string in logs,
- F-strings are eager, so might be slow.
- prevent structured logging or handler to highlight.
- Security (untrusted input can lead to DOS on formatting, https://discuss.python.org/t/safer-logging-methods-for-f-strings-and-new-style-formatting/13802)
- Performance (we can filter before formatting).
But also % formatting in a couple of places.
See jupyter_client/jupyter_client#919 ipython/ipython#13903
=> MAINT: Don't format logs in log call.

examples/jupyter-completion.bash, jupyter_core/command.py, jupyter_core/migrate.py, jupyter_core/troubleshoot.py, scripts/jupyter-migrate
Set up shell command-line tab-completion using `argcomplete` and ipython/traitlets#811. Completion requires `argcomplete` to be activated and `traitlets>=5.8`. Behavior is only changed when `$_ARGCOMPLETE` is set, so there should be no difference in behavior otherwise.
For subcommand handling, this will use `list_subcommands()` to try to complete the first argument if it doesn't start with a "-", and when a subcommand is detected, `argcomplete` will increment the start of the command-line handling past the subcommand and drop into the relevant `traitlets.Application`'s argcomplete handling. All of the major subcommands like `jupyter lab` directly use `traitlets.Application.launch_instance` so this works pretty seamlessly. However, completing commands that start with the hyphenated …
=> Set up shell command-line tab-completion for jupyter and subcommands

.github/workflows/test.yml, README.md, codecov.yml, pyproject.toml
cf https://github.com/jupyterlab/maintainer-tools/pull/189
=> Use local coverage

jupyter_core/application.py, jupyter_core/tests/test_migrate.py
better than just checking if it exists, because some on some platforms (e.g. ro AFS on HPC ) os.path.exists() may give False just because os.stat fails, even though the file actually exists
Also adds more test coveraate of the migrated marker checking
Fixes #355
=> Better handling of config migration

jupyter_core/application.py, jupyter_core/utils/__init__.py, pyproject.toml
Fixes https://github.com/jupyter/jupyter_client/issues/959
Fixes https://github.com/spyder-ide/spyder/issues/21338
=> Fix event loop handling

jupyter_core/application.py
=> Account for read only file systems in migration

jupyter_core/application.py, jupyter_core/paths.py, jupyter_core/utils/__init__.py, tests/test_application.py
- Start an event loop before calling `initialize` and `start` on the app.
- Add `initialize_async` and `start_async` that will be called after their sync versions.
- Expose a `get_event_loop` utility function that gets or sets the event loop for the current thread.
See https://github.com/jupyter/jupyter_client/pull/997 and https://github.com/jupyter-server/jupyter_server/issues/1362 for context.
=> Enable async JupyterApp

.github/workflows/downstream.yml, jupyter_core/application.py, jupyter_core/utils/__init__.py, tests/test_application.py, tests/test_utils.py
Based on discussion in https://github.com/python/cpython/issues/100160, we should not be relying on `asyncio.get_event_loop`, since they are in fact going to make it an alias for `asyncio.get_running_loop`.
This ensures we install an event loop before launching our apps, so we should not see any more issues like https://github.com/jupyter/notebook/issues/6721.
Additionally, it adds a new class, `JupyterAsyncApp` that runs `initialize_async()` and `start_async()` in an event loop.
Based on results in https://github.com/ipython/ipykernel/pull/1184, we'll want to normally use the default event loop on Windows, unless we know we're running a tornado app.  This PR adds a `prefer_selector_loop` option to `ensure_event_loop` so we can override `_prefer_selector_loop` in `jupyter_server` apps to …
=> Modernize event loop behavior

.readthedocs.yaml, docs/conf.py, pyproject.toml
- remove sphinxcontrib_github_alt as it is unused since 5c51ceb6b5516dc330c8311e2b6708fb1f25c5f5
- bump used python in a few places.
- and start using intersphinx_registry to simplify managing intersphinx.
=> Miscelaneous docs update.

docs/conf.py, jupyter_core/utils/__init__.py
assert are meant to be always true – but should be
disabled when running with Python optimisations.
That is to say an optimised run should not raise an assertion error.
This is misusing assertions.
-- 
Also github_project_url is not a sphinx config option anymore.
=> AssertionErrors should not be manually raised.

jupyter_core/paths.py, pyproject.toml
it's guaranteed to be bool unless `default=None`, reflect that with overload
removes some unneeded type:ignores
=> narrow type of envset when it can't be None

.github/workflows/test.yml, jupyter_core/paths.py, jupyter_core/utils/__init__.py, pyproject.toml, tests/test_migrate.py
Reverts jupyter/jupyter_core#426
I actually want to make a release first, then do this
=> Revert "breaking: require Python 3.9"

.github/workflows/test.yml, jupyter_core/paths.py, jupyter_core/utils/__init__.py, pyproject.toml, tests/test_migrate.py
re-issue #426 after 5.8.0 release (last release for Python 3.8)
=> breaking: require Python 3.9

jupyter_core/paths.py, tests/test_paths.py
SYSTEM_CONFIG_PATH hasn't technically been guaranteed to be non-empty, but jupyter-server has assumed it is: https://github.com/jupyter-server/jupyter_server/issues/1527 and in practice, it ~always has been until 5.8 because the empty case was weird and rare.
We already use sys.prefix for SYSTEM_JUPYTER_PATH in a similar situation, so it's probably simplest to do the same in config path.
cc @krassowski
I can do a 5.8.1 with this.
=> use env config path for system config path when no system config path

docs/conf.py
This is possible since sphinx 1.8, and avoid the message:
>  "Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`"
at docs build time. See https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-source_suffix
=> [Docs] Use extension:filetype mapping in sphinx configuration
